#!/bin/bash
echo ""[D “Hello, World”[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[C[C"[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C""[D“Hello, World”[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[[C[D"[[C[[C[C[C[C[C[C[C[C[C[C[C[""[D [D[CHello,wo[D[D [World"[D[D[D[D[D[D[C[C[C[C[C[C[C
