#!/bin/bash
Create a script that removes all letters c and C from input.

[A[A[B[D[D[D[C[D[D[D[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Crev
